[package]
name = "client"
version = "0.1.0"
authors = ["Oleksandr Tkachov <theopus5@gmail.com>"]
edition = "2018"

#wasm32
#[lib]
#crate-type = ["cdylib"]

#wasm32
#[dependencies]
#wasm-bindgen="0.2"
[dependencies.rx_engine]
path = "../core"
features = ["imgui_debug"]
