[package]
name = "rx_engine"
version = "0.1.0"
authors = ["Oleksandr Tkachov <v-otkachov@expediagroup.com>"]
edition = "2018"

[dependencies.specs]
version = "0.15.0"
[dependencies.gl]
path = "../gl"
[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"
